---
# This handles the loading of my automations
#
# https://www.home-assistant.io/docs/automation/
#
automation: !include ../includes/automations.yaml
automation split: !include_dir_list ../automations
