# We have an dedicated alarm system and not going to use these z-wave
# features; ignore.
"*_burglar*":
  ignored: true
  polling_intensity: 0
"*_alarm_type":
  ignored: true
  polling_intensity: 0
"*_alarm_level":
  ignored: true
  polling_intensity: 0

# Not sure why this is useful... I don't use it; ignore.
"*_sourcenodeid":
  ignored: true

# Fibaro switches have an exporting sensor... I don't use it; ignore.
"sensor.*_exporting":
  ignored: true
